### ISSUE TITLE
Empty DLL

### ISSUE THREAD

**Issue by ltrzesniewski** [rverdier/funsafe#1]
Your project looks very nice. I tried to compile it with the following command:

```
> csc /target:library /out:funsafe.dll
```

But the produced `funsafe.dll` contains no classes. Not even one. Do you think it might be related to the fact there is no source code in commit `e6f3b5f`?

`</lol>` :stuck_out_tongue_winking_eye:

**Comment by rverdier** [comment]
Weird... It works on my machine.
